version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: Park-Hub
    environment:
      POSTGRES_DB: Park-Api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"