spring:
  application:
    name: Park-Api

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/Park-Api
    username: postgres
    password: admin

  flyway:
    enabled: true
    locations: classpath:db/migration

  web:
    locale-resolver: fixed
    locale: pt_BR